version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - myvolume:/redisData
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 5
  web:
    image: ametizs/devops ##name of the image
    ports:
      - "5000:3000"
    volumes:
      - myvolume:/data
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: on-failure
    depends_on:
      redis: 
        condition: service_healthy
    links:
      - redis
volumes:
  myvolume:
