apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project-devops-deployment
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-devops
      version: v1
  template:
    metadata:
      labels:
        app: project-devops
        version: v1
    spec:
      containers:
        - name: project-devops
          image: ametizs/devops
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: project-devops-service
spec:
  selector:
    app: project-devops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
      

     
