---
- hosts: ubuntu_server
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: app/database
    tags: install
  - role: app/node
    tags: install
  - role: app/install
    tags: install
  - role: app/healthchecks
    tags: healthchecks